# Generated by Django 2.2.5 on 2020-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(default='讲师', max_length=50, verbose_name='职位'),
        ),
    ]
